### PR TITLE
LRQA-83045

### PR DESCRIPTION
**Pull request by crislucas1**
https://liferay.atlassian.net/browse/LRQA-83045

### CODE REVIEW

**Comment by crislucas1** [comment]
ci:test:sf

**Comment by crislucas1** [comment]
ci:test:cf

**Comment by crislucas1** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, @crislucas1. Thanks for working on this. Congratulations 🎉 

PS: I have some improvements, but I'll put them in the last [PR](https://github.com/ViniLopes20/liferay-portal/pull/183/files)

**Pull request closed without merging**
